import type { LegalWorkPlanTypeConfig } from "@/types/safetyCardTypes";

export const legalWorkPlanTypes: LegalWorkPlanTypeConfig[] = [
  {
    id: "towerCraneAssembly",
    label: "타워크레인 설치·조립·해체 작업",
    category: "중장비",
    legalBasisText: "산업안전보건기준에 관한 규칙 제142조",
    description: "타워크레인의 설치·조립·해체 시 작성해야 하는 법정 작업계획서",
    requiredSections: [
      "타워크레인 작업계획", "작업순서", "작업도구·장비·가설설비",
      "방호설비", "작업인원 구성 및 역할", "지지방법",
      "추락방지", "낙하방지", "풍속 확인", "작업지휘자", "신호체계",
    ],
    defaultHazards: ["추락", "낙하물", "강풍에 의한 전도", "인양하중 초과"],
    defaultControls: ["안전대 착용", "낙하물 방지망", "풍속 기준 초과 시 작업중지", "신호수 배치"],
    requiredRoles: ["작업지휘자", "신호수", "인양작업자"],
    recommendedInspections: ["타워크레인 일상점검", "풍속 측정", "볼트 체결 확인"],
    recommendedTrainings: ["타워크레인 안전교육", "고소작업 안전교육"],
    icon: "🏗",
  },
  {
    id: "vehicleHandling",
    label: "차량계 하역운반기계등 사용 작업",
    category: "차량계",
    legalBasisText: "산업안전보건기준에 관한 규칙 제178조",
    description: "지게차, 구내운반차, 화물자동차 등 하역운반기계 사용 작업",
    requiredSections: [
      "운행경로", "작업방법", "적재물 정보", "적재량 검토",
      "보행자 동선 분리", "유도자 배치", "후진 작업 여부",
      "낙하방지 조치", "전도방지 조치", "제한속도", "사전점검표",
    ],
    defaultHazards: ["충돌", "협착", "전도", "적재물 낙하"],
    defaultControls: ["유도자 배치", "제한속도 설정", "후방감지 장치", "안전벨트 착용"],
    requiredRoles: ["유도자", "운전원"],
    recommendedInspections: ["제동장치 점검", "적재 상태 확인", "후방카메라 작동 확인"],
    recommendedTrainings: ["차량계 하역운반기계 안전교육", "협착 예방 교육"],
    icon: "🚛",
  },
  {
    id: "constructionMachine",
    label: "차량계 건설기계 사용 작업",
    category: "차량계",
    legalBasisText: "산업안전보건기준에 관한 규칙 제196조",
    description: "굴착기, 불도저, 로더 등 차량계 건설기계 사용 작업",
    requiredSections: [
      "작업장소 지형 및 지반상태", "사용하는 기계 종류 및 성능",
      "운행경로", "작업방법", "장비 배치", "신호수", "작업반경 출입통제", "사전점검표",
    ],
    defaultHazards: ["전도", "충돌", "협착", "지반 침하"],
    defaultControls: ["신호수 배치", "작업반경 통제", "지반 보강", "안전속도 준수"],
    requiredRoles: ["운전원", "신호수"],
    recommendedInspections: ["기계 사전점검", "작업반경 장애물 확인"],
    recommendedTrainings: ["차량계 건설기계 안전교육"],
    icon: "🚧",
  },
  {
    id: "chemicalFacility",
    label: "화학설비 및 부속설비 사용 작업",
    category: "화학",
    legalBasisText: "산업안전보건기준에 관한 규칙 제273조",
    description: "화학설비 및 부속설비의 정비·보수·청소 등 작업",
    requiredSections: [
      "밸브·콕 조작계획", "냉각·가열·교반·압축 장치 조작",
      "계측·제어 장치 감시", "안전밸브·긴급차단장치 점검",
      "접합부 누출 점검", "시료 채취 방법",
      "운전 중단 및 재개 절차", "이상상태 응급조치",
      "위험물 누출 시 조치", "폭발·화재 방지조치",
    ],
    defaultHazards: ["가스 누출", "폭발", "화재", "화학물질 접촉"],
    defaultControls: ["방호장구 착용", "가스 감지기 설치", "비상대피 계획", "MSDS 비치"],
    requiredRoles: ["작업책임자", "안전관리자"],
    recommendedInspections: ["가스 누출 측정", "화재감지기 작동 확인"],
    recommendedTrainings: ["화학물질 취급 안전교육", "화재진압 교육"],
    icon: "⚗",
  },
  {
    id: "electrical",
    label: "전기작업",
    category: "전기",
    legalBasisText: "산업안전보건기준에 관한 규칙 제319조",
    description: "전기설비 설치·해체·점검·수리 및 활선/정전 작업",
    requiredSections: [
      "작업 목적", "근로자 자격", "적정 인원", "작업 범위", "작업책임자",
      "전기 위험요인", "전로차단 작업계획", "LOTO 절차",
      "검전", "접지", "절연보호구", "전원 재투입 절차", "출입금지 조치",
    ],
    defaultHazards: ["감전", "아크 플래시", "전기 화재"],
    defaultControls: ["LOTO 실시", "검전기 사용", "절연보호구 착용", "접지 설치"],
    requiredRoles: ["전기 작업책임자", "감시인"],
    recommendedInspections: ["절연저항 측정", "접지 상태 확인", "보호구 이상 여부"],
    recommendedTrainings: ["전기 안전교육", "LOTO 교육", "응급처치 교육"],
    icon: "⚡",
  },
  {
    id: "excavation",
    label: "굴착작업",
    category: "토공",
    legalBasisText: "산업안전보건기준에 관한 규칙 제337조",
    description: "굴착면의 높이가 2m 이상인 굴착작업",
    activationCondition: "굴착면 높이 2m 이상",
    requiredSections: [
      "굴착 위치", "굴착 깊이·폭·연장", "굴착 기울기",
      "지질·지층·토질", "균열·함수·용수·동결", "지하수위",
      "매설물 확인", "굴착 순서", "토사 반출", "흙막이 지보공",
      "계측계획", "작업지휘자", "연락 및 신호방법",
    ],
    defaultHazards: ["토사 붕괴", "매설물 파손", "작업자 매몰", "지하수 용출"],
    defaultControls: ["흙막이 설치", "매설물 확인", "계측 관리", "비상대피 계획"],
    requiredRoles: ["작업지휘자", "계측 담당자"],
    recommendedInspections: ["굴착면 상태 점검", "흙막이 변형 측정", "지하수위 확인"],
    recommendedTrainings: ["굴착작업 안전교육", "붕괴·매몰 예방 교육"],
    icon: "⛏",
  },
  {
    id: "tunnel",
    label: "터널굴착작업",
    category: "토공",
    legalBasisText: "산업안전보건기준에 관한 규칙 제352조",
    description: "터널 굴착, 지보 설치, 복공 등 터널 관련 작업",
    requiredSections: [
      "사전조사 결과", "굴착 방법", "터널 지보공 시공방법",
      "복공 시공방법", "용수 처리방법", "환기시설 설치방법",
      "조명시설 설치방법", "비상대피 및 응급처치 계획",
    ],
    defaultHazards: ["낙반", "용출수", "유해가스", "발파 비산"],
    defaultControls: ["락볼트 설치", "환기 실시", "가스 측정", "대피로 확보"],
    requiredRoles: ["작업지휘자", "환기 관리자"],
    recommendedInspections: ["터널 천장 안전 점검", "가스 측정", "환기 설비 작동 확인"],
    recommendedTrainings: ["터널 안전교육", "밀폐공간 안전교육"],
    icon: "🚇",
  },
  {
    id: "bridge",
    label: "교량 설치·해체·변경 작업",
    category: "구조물",
    legalBasisText: "산업안전보건기준에 관한 규칙 제373조",
    description: "높이 5m 이상 또는 최대 지간 30m 이상 교량 설치·해체·변경 작업",
    activationCondition: "높이 5m 이상 또는 최대 지간 30m 이상",
    requiredSections: [
      "작업 위치", "작업 구분", "구조 안정성", "추락방지", "낙하물 방지",
      "가설구조물", "인양계획", "교통통제", "기상조건", "비상구조계획",
    ],
    defaultHazards: ["추락", "낙하물", "구조물 전도", "교통 사고"],
    defaultControls: ["안전난간 설치", "낙하물 방지망", "교통통제", "안전대 착용"],
    requiredRoles: ["작업지휘자", "교통통제원"],
    recommendedInspections: ["가설구조물 안전 점검", "인양장비 사전점검"],
    recommendedTrainings: ["고소작업 안전교육", "중량물 취급 안전교육"],
    icon: "🌉",
  },
  {
    id: "quarry",
    label: "채석작업",
    category: "토공",
    legalBasisText: "산업안전보건기준에 관한 규칙 제389조",
    description: "채석장에서의 채석 및 관련 작업",
    requiredSections: [
      "채석 위치", "절취면 상태", "암반 상태", "발파 여부", "낙석위험",
      "장비 운행경로", "작업반경 통제", "분진 저감", "대피계획", "신호방법",
    ],
    defaultHazards: ["낙석", "발파 비산", "분진", "장비 전도"],
    defaultControls: ["낙석 방지망", "발파 안전거리", "방진마스크", "대피계획"],
    requiredRoles: ["작업지휘자", "발파 담당자"],
    recommendedInspections: ["절취면 안전 점검", "장비 사전점검"],
    recommendedTrainings: ["채석작업 안전교육", "발파 안전교육"],
    icon: "🪨",
  },
  {
    id: "demolition",
    label: "구축물·건축물 등 해체작업",
    category: "해체",
    legalBasisText: "산업안전보건기준에 관한 규칙 제420조",
    description: "구축물·건축물·공작물 등의 해체 작업",
    requiredSections: [
      "해체 대상 구조물 정보", "해체 방법", "해체 순서",
      "구조 안정성 검토", "가설설비", "방호설비",
      "살수·방화설비", "연락방법", "해체물 처분계획", "해체장비", "출입통제",
    ],
    defaultHazards: ["구조물 붕괴", "낙하물", "분진", "소음·진동"],
    defaultControls: ["해체 순서 준수", "방호 설비 설치", "출입통제", "분진 억제"],
    requiredRoles: ["작업지휘자", "안전관리자"],
    recommendedInspections: ["구조물 안전 점검", "방호 설비 확인"],
    recommendedTrainings: ["해체작업 안전교육"],
    icon: "🔨",
  },
  {
    id: "heavyLoad",
    label: "중량물 취급작업",
    category: "중량물",
    legalBasisText: "산업안전보건기준에 관한 규칙 제167조",
    description: "중량물(무게 50kg 이상) 취급 시 작성해야 하는 법정 작업계획서",
    requiredSections: [
      "취급 방법", "사용 장비", "양중물 정보",
      "추락위험 예방대책", "낙하위험 예방대책", "전도위험 예방대책",
      "협착위험 예방대책", "붕괴위험 예방대책",
    ],
    defaultHazards: ["중량물 낙하", "작업자 협착", "장비 전도", "줄걸이 파단"],
    defaultControls: ["정격하중 검토", "신호수 배치", "작업반경 통제", "줄걸이 점검"],
    requiredRoles: ["신호수", "인양 담당자"],
    recommendedInspections: ["인양장비 사전점검", "줄걸이 이상 여부 확인"],
    recommendedTrainings: ["중량물 취급 안전교육", "크레인 신호 교육"],
    icon: "🏋",
  },
  {
    id: "railwayTrack",
    label: "궤도 및 관련 설비 보수·점검작업",
    category: "궤도",
    legalBasisText: "산업안전보건기준에 관한 규칙 제452조",
    description: "철도·궤도 및 관련 설비의 보수·점검 작업",
    requiredSections: [
      "작업 구간", "열차 운행 여부", "선로 차단 또는 작업 승인",
      "감시자", "신호수", "장비 사용", "감전위험", "협착위험", "야간작업", "비상대피",
    ],
    defaultHazards: ["열차 충돌", "감전", "협착", "야간 시야 불량"],
    defaultControls: ["선로 차단", "감시자 배치", "절연보호구", "조명 설치"],
    requiredRoles: ["작업책임자", "감시자"],
    recommendedInspections: ["선로 차단 확인", "보호구 점검"],
    recommendedTrainings: ["궤도작업 안전교육"],
    icon: "🚃",
  },
  {
    id: "trainShunting",
    label: "열차 입환작업",
    category: "궤도",
    legalBasisText: "산업안전보건기준에 관한 규칙 제457조",
    description: "열차 입환(차량 이동·연결·분리) 작업",
    requiredSections: [
      "입환 작업 구간", "교환·연결·분리 대상", "신호체계",
      "작업자 배치", "열차 운행 협의", "감시자", "비상정지 방법", "접근금지 조치",
    ],
    defaultHazards: ["열차 충돌", "협착", "작업자 추락"],
    defaultControls: ["신호체계 수립", "접근금지 조치", "감시자 배치"],
    requiredRoles: ["입환 책임자", "감시자"],
    recommendedInspections: ["신호체계 확인", "제동장치 점검"],
    recommendedTrainings: ["열차 입환 안전교육"],
    icon: "🚂",
  },
];
