import type { RiskWorkAttributeConfig } from "@/types/safetyCardTypes";

export const riskWorkAttributes: RiskWorkAttributeConfig[] = [
  {
    id: "heightWork",
    label: "고소작업",
    description: "지면으로부터 2m 이상 높이에서의 작업",
    sections: ["작업높이", "추락위험 위치", "작업발판", "안전대/안전블록", "난간/개구부 덮개", "하부 출입통제", "풍속/기상조건", "비상구조"],
    defaultHazards: ["추락", "낙하물", "강풍에 의한 작업 불안정"],
    defaultControls: ["안전대 착용 및 체결", "안전난간 설치", "하부 출입통제", "풍속 기준 초과 시 작업중지"],
    recommendedInspections: ["안전대 이상 유무 점검", "작업발판 상태 점검", "안전난간 설치 여부"],
    recommendedTrainings: ["추락재해 예방 교육", "고소작업 안전교육"],
    icon: "🪜",
  },
  {
    id: "hotWork",
    label: "화기작업",
    description: "불꽃, 화염, 열을 발생시키는 용접·용단·연삭 등의 작업",
    sections: ["화기작업 종류", "인화성 물질 확인", "가연물 제거", "소화기 배치", "불티 비산방지", "환기", "화재감시자", "작업 후 잔불 확인", "화기작업 허가"],
    defaultHazards: ["화재", "폭발", "화상", "유해가스 흡입"],
    defaultControls: ["화기작업 허가서 발행", "소화기 비치", "가연물 제거 또는 방호", "화재감시자 배치", "불티 비산방지 포 설치"],
    recommendedInspections: ["소화기 충전 상태 확인", "인화성 물질 격리 확인", "환기 상태 확인"],
    recommendedTrainings: ["화재예방 안전교육", "소화기 사용법 교육"],
    icon: "🔥",
  },
  {
    id: "confinedSpace",
    label: "밀폐공간 작업",
    description: "산소결핍 또는 유해가스 위험이 있는 밀폐공간 내 작업",
    sections: ["밀폐공간 위치", "산소농도", "유해가스 측정", "환기계획", "출입자 관리", "감시인", "구조장비", "통신방법", "출입허가"],
    defaultHazards: ["산소결핍으로 인한 질식", "유해가스 중독", "폭발"],
    defaultControls: ["작업 전 산소·유해가스 측정", "강제 환기 실시", "감시인 배치", "구조장비 비치", "출입허가서 발행"],
    recommendedInspections: ["산소농도 측정(18% 이상)", "유해가스 측정", "환기 설비 작동 확인"],
    recommendedTrainings: ["밀폐공간 작업 안전교육", "구조 및 응급처치 교육"],
    icon: "🕳",
  },
  {
    id: "nightWork",
    label: "야간작업",
    description: "일출 전 또는 일몰 후에 시행하는 작업",
    sections: ["조도", "조명계획", "야간 신호체계", "피로관리"],
    defaultHazards: ["시야 불량으로 인한 사고", "작업자 피로"],
    defaultControls: ["적정 조도 확보(150lux 이상)", "야광 조끼 착용", "작업 전 안전 브리핑"],
    recommendedInspections: ["조명 상태 점검", "작업구역 조도 측정"],
    recommendedTrainings: ["야간작업 안전교육"],
    icon: "🌙",
  },
  {
    id: "rainWork",
    label: "우천작업",
    description: "강우 중 또는 강우 후 지면 등이 미끄러운 상태에서의 작업",
    sections: ["미끄럼 방지", "감전위험", "배수계획", "작업중지 기준"],
    defaultHazards: ["미끄럼으로 인한 추락", "감전", "수분으로 인한 기계 오작동"],
    defaultControls: ["미끄럼 방지 신발 착용", "전기기기 방수 처리", "배수로 확보", "강우량 기준 초과 시 작업중지"],
    recommendedInspections: ["배수 상태 확인", "전기기기 방수 상태 확인"],
    recommendedTrainings: ["우천·악천후 작업 안전교육"],
    icon: "🌧",
  },
  {
    id: "strongWindWork",
    label: "강풍 노출 작업",
    description: "풍속 10m/s 이상 또는 순간풍속 15m/s 이상에서의 작업",
    sections: ["풍속", "작업중지 기준", "자재 결속", "낙하물 방지"],
    defaultHazards: ["구조물 전도", "낙하물 비산", "고소작업자 추락"],
    defaultControls: ["풍속 측정 후 작업 판단", "자재 결속 강화", "낙하물 방지망 설치", "풍속 기준 초과 시 작업중지"],
    recommendedInspections: ["풍속 측정", "자재 결속 상태 확인"],
    recommendedTrainings: ["강풍 상황 안전교육"],
    icon: "💨",
  },
  {
    id: "simultaneousWork",
    label: "동시작업",
    description: "동일 장소에서 2개 이상의 작업이 동시에 진행되는 경우",
    sections: ["인접작업 현황", "작업 간섭위험", "작업조정자", "동시작업 통제계획"],
    defaultHazards: ["작업 간 충돌", "낙하물 피해", "신호 혼선"],
    defaultControls: ["작업조정자 배치", "작업 구역 명확 분리", "신호체계 통일"],
    recommendedInspections: ["작업구역 구분 상태 확인", "신호체계 확인"],
    recommendedTrainings: ["동시작업 안전교육"],
    icon: "🔄",
  },
  {
    id: "adjacentWork",
    label: "인접작업",
    description: "인접한 설비, 구조물, 작업자 근처에서 진행되는 작업",
    sections: ["인접 설비", "인접 작업자", "출입통제", "충돌/접촉 방지"],
    defaultHazards: ["인접 설비 접촉", "다른 작업자와 충돌"],
    defaultControls: ["인접 설비 격리", "출입통제 실시", "안전거리 확보"],
    recommendedInspections: ["인접 설비 이격거리 확인"],
    recommendedTrainings: ["인접작업 안전교육"],
    icon: "↔",
  },
  {
    id: "liveElectricalWork",
    label: "활선작업",
    description: "전기가 통하는 상태에서 전기설비를 다루는 작업",
    sections: ["접근한계거리", "절연보호구", "활선작업용 기구", "감시자"],
    defaultHazards: ["감전", "아크 플래시", "전기 화재"],
    defaultControls: ["절연보호구 착용", "접근한계거리 유지", "감시자 배치"],
    recommendedInspections: ["절연보호구 절연내력 확인", "활선작업기구 이상 유무"],
    recommendedTrainings: ["활선작업 안전교육", "감전 응급처치 교육"],
    icon: "⚡",
  },
  {
    id: "blackoutElectricalWork",
    label: "정전작업",
    description: "전기를 차단한 상태에서 전기설비를 다루는 작업",
    sections: ["차단계획", "LOTO", "검전", "접지", "재투입 절차"],
    defaultHazards: ["전로 미차단 감전", "갑작스러운 전원 투입"],
    defaultControls: ["LOTO 실시", "검전기로 무전압 확인", "접지 설치", "재투입 절차 수립"],
    recommendedInspections: ["LOTO 적용 상태 확인", "검전 결과 확인"],
    recommendedTrainings: ["LOTO 교육", "정전작업 안전교육"],
    icon: "🔌",
  },
  {
    id: "blastingWork",
    label: "발파작업",
    description: "화약류를 사용한 발파 작업",
    sections: ["화약류 관리", "발파통제", "대피계획", "신호방법"],
    defaultHazards: ["발파 비산", "불발탄", "지반 진동"],
    defaultControls: ["대피계획 수립", "불발탄 처리 계획", "발파 신호 체계"],
    recommendedInspections: ["화약류 보관 상태", "발파 구역 확인"],
    recommendedTrainings: ["발파 안전교육", "화약류 취급 교육"],
    icon: "💥",
  },
  {
    id: "waterWork",
    label: "수상작업",
    description: "강, 하천, 해상 등 수면 위 또는 수중에서의 작업",
    sections: ["구명조끼", "추락/익수 대응", "구조장비", "기상조건"],
    defaultHazards: ["익사", "수중 충돌", "급격한 기상 변화"],
    defaultControls: ["구명조끼 착용", "구조보트 배치", "기상 확인 후 작업"],
    recommendedInspections: ["구명조끼 상태 확인", "구조장비 작동 확인"],
    recommendedTrainings: ["수상작업 안전교육", "수중구조 교육"],
    icon: "🌊",
  },
  {
    id: "undergroundWork",
    label: "지하작업",
    description: "지하 공간, 수로, 하수도 등 지하 구조물 내부 작업",
    sections: ["환기", "조명", "비상대피", "통신"],
    defaultHazards: ["산소결핍", "유해가스", "폭발", "침수"],
    defaultControls: ["환기 실시", "가스 측정", "비상 대피로 확보", "통신 수단 확보"],
    recommendedInspections: ["환기 상태 확인", "가스 농도 측정"],
    recommendedTrainings: ["지하작업 안전교육", "밀폐공간 안전교육"],
    icon: "🏚",
  },
  {
    id: "trafficControlWork",
    label: "도로점용·교통통제 작업",
    description: "도로를 점용하거나 교통을 통제하며 진행하는 작업",
    sections: ["교통통제 계획", "신호수", "표지판", "작업구역 분리"],
    defaultHazards: ["차량 충돌", "보행자 사고", "작업자 부상"],
    defaultControls: ["신호수 배치", "안전 표지판 설치", "작업구역 방호울타리"],
    recommendedInspections: ["교통통제 설비 상태 확인", "신호수 배치 확인"],
    recommendedTrainings: ["교통통제 안전교육"],
    icon: "🚦",
  },
];
